apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  clusterIP: None  # Headless service (Each Pod can be reached individually — ideal for things like databases)
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
